#include<iostream>
using namespace std;
convert(string num);
main(){
    int num;
    cout<<"Enter a number (1-99):";
    cin>>num;
    convert(num);
}
convert(string num)
{
    if(num==1)
    {cout<<"One";}
    if(num==2)
    {cout<<"Two";}
    if(num==3)
    {cout<<"Three";}
    if(num==4)
    {cout<<"Four";}
    if(num==5)
    {cout<<"Five";}
    if(num==6)
    {cout<<"Six";}
    if(num==7)
    {cout<<"Seven";}
    if(num==8)
    {cout<<"Eight";}
    if(num==9)
    {cout<<"Nine";}
    if(num==10)
    {cout<<"Ten";}
    if(num==11);
    {cout<<"Eleven";}
    if(num==12);
    {cout<<"Twelve";}
    if(num==13);
    {cout<<"Thirteen";}
    if(num==14);
    {cout<<"Fourteen";}
    if(num==15);
    {cout<<"Fifteen";}
    if(num==16);
    {cout<<"Sixteen";}
    if(num==17);
    {cout<<"Seventeen";}
    if(num==18);
    {cout<<"Eighteen";}
    if(num==19);
    {cout<<"Ninteen";}
    if(num==20);
    {cout<<"Twenty";}
    if(num==21);
    {cout<<"TwentyOne";}
    if(num==22);
    {cout<<"TwentyTwo";}
    if(num==23);
    {cout<<"TwentyThree";}
    if(num==24);
    {cout<<"TwentyFour";}
    if(num==25);
    {cout<<"TwentyFive";}
    if(num==26);
    {cout<<"TwentySix";}
    if(num==27);
    {cout<<"TwentySeven";}
    if(num==28);
    {cout<<"TwentyEight";}
    if(num==29);
    {cout<<"TwentyNine";}
    if(num==30);
    {cout<<"Thirty";}
    if(num==31);
    {cout<<"ThirtyOne";}
    if(num==32);
    {cout<<"ThirtyTwo";}
    if(num==33);
    {cout<<"ThirtyThree";}
    if(num==34);
    {cout<<"ThirtFour";}
    if(num==35);
    {cout<<"ThirtyFive";}
    if(num==36);
    {cout<<"ThirtySix";}
    if(num==37);
    {cout<<"ThirtySeven";}
    if(num==38);
    {cout<<"ThirtyEight";}
    if(num==39);
    {cout<<"ThirtyNine";}
    if(num==40);
    {cout<<"Fourty";}
    if(num==41);
    {cout<<"FourtyOne";}
    if(num==42);
    {cout<<"FourtyTwo";}
    if(num==43);
    {cout<<"FourtyThree";}
    if(num==44);
    {cout<<"FourtyFour";}
    if(num==45);
    {cout<<"FourtyFive";}
    if(num==46);
    {cout<<"FourtySix";}
    if(num==47);
    {cout<<"FourtySeven";}
    if(num==48);
    {cout<<"FourtyEight";}    
    if(num==49);
    {cout<<"FourtyNine";}
    if(num==50);
    {cout<<"Fifty";}
    if(num==51);
    {cout<<"FiftyOne";}
    if(num==52);
    {cout<<"FiftyTwo";}
    if(num==53);
    {cout<<"FiftyThree";}
    
    
    
    
